# ASP.NET Core (.NET Framework)


# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.x'
    includePreviewVersions: true

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.1.0'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*nUnit/*.csproj'
    feedsToUse: 'select'
    noCache: true

- task: DotNetCoreCLI@2
  inputs:
   command: test
   projects: '**/*nUnit/*.csproj'
   arguments: '--configuration $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build test'
  inputs:
    projects: '**/*nUnit/*.csproj'
    arguments: '--runtime win-x64'
  continueOnError: true

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2 
  displayName: 'dotnet publish test --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)' 
  inputs: 
    command: publish 
    publishWebProjects: false 
    projects: 'Salon/Salon.nUnit/Salon.nUnit.csproj' 
    arguments: '-p:PublishChromeDriver=true --runtime win-x64 --output $(Build.ArtifactStagingDirectory)/TechFabricSln.Test/' 
    zipAfterPublish: false 

- task: PublishBuildArtifacts@1 
  displayName: 'publish artifacts'
